// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  intro: dynamic(() => import("./Intro")),
  project: dynamic(() => import("./Project")),
  selected_work: dynamic(() => import("./SelectedWork")),
};
